# Basic dependabot configuration for NPM

version: 1
updates:

  # Enable version updates for npm
  - package-ecosystem: "npm"

    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"

    # Check the npm registry for updates every day at midnight
    schedule:
      interval: "daily"
      time: "00:00"

    # Check only for security updates
    allowed_updates:
      - match:
          update_type: "security"
